{
  "message": "[Errno 5] Input/output error",
  "traceback": "Traceback (most recent call last):\n  File \"/home/vagrant/treeherder-service/treeherder/webapp/api/views.py\", line 126, in use_jobs_model\n    return model_func(*args, jm=jm, **kwargs)\n  File \"/home/vagrant/treeherder-service/treeherder/webapp/api/views.py\", line 405, in list\n    return Response(self.get_resultsets_with_jobs(jm, objs, full, {}))\n  File \"/home/vagrant/treeherder-service/treeherder/webapp/api/views.py\", line 448, in get_resultsets_with_jobs\n    **filter_kwargs\n  File \"/home/vagrant/treeherder-service/treeherder/model/derived/jobs.py\", line 535, in get_result_set_job_list\n    replace=repl,\n  File \"/home/vagrant/treeherder-service/vendor/datasource/bases/RDBSHub.py\", line 71, in wrapper\n    return func(self, **kwargs)\n  File \"/home/vagrant/treeherder-service/vendor/datasource/bases/SQLHub.py\", line 136, in execute\n    return self.__execute(sql, kwargs)\n  File \"/home/vagrant/treeherder-service/vendor/datasource/bases/SQLHub.py\", line 298, in __execute\n    tmsg)\n  File \"/home/vagrant/treeherder-service/vendor/datasource/bases/RDBSHub.py\", line 436, in show_debug\n    sys.stdout.write( unicode(msg).encode(\"utf-8\") )\nIOError: [Errno 5] Input/output error\n"
}
